# This is a basic workflow to help you get started with Actions

name: CI
env:
  EM_VERSION: 3.1.1
  EM_CACHE_FOLDER: 'emsdk-cache'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: Build library
        run: make
      - name: Bundle
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm install
          npm pack
          echo "NPM_TGZ=$(ls h5wasm*.tgz)" >> $GITHUB_ENV
      - name: Bundle libhdf5
        run: tar -C wasm_build/hdf5/ -czf libhdf5_wasm.tgz include lib
      - name: Upload libhdf5
        uses: actions/upload-artifact@v2
        with:
          path: libhdf5_wasm.tgz
      - name: Update current release
        if: startsWith(github.ref, 'refs/tags')
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            libhdf5_wasm.tgz
            ${{ env.NPM_TGZ }}
